### ISSUE TITLE
关于yilia-l主题的字体

### ISSUE THREAD

**Issue by konelane** [Kiritor/hexo-theme-yilia-l#1]
大神好，我是一名学生，用yilia-l这个主题一年了，很舒服！
最近想添加点花哨的装饰，比如更换字体之类。
我是前端小白，不曾接触过js，所以代码就有点看不懂了。
请问大神可以在主题配置文件里加入字体的控制吗？秋梨膏！

**Comment by Kiritor** [comment]
先告诉我秋梨膏是什么梗

**Comment by konelane** [comment]
哈哈哈哈，原梗是：A1高闪来一个好吗？秋梨膏！（求你了）
语出斗鱼csgo主播茄子(//∇//)

王源禾
中央财经大学统计与数学学院
电话:  18810920968  
博客:  https://konelane.github.io/  
---原始邮件---
发件人: "L.Tao"<notifications@github.com>
发送时间: 2019年6月5日(星期三) 中午12:54
收件人: "Kiritor/hexo-theme-yilia-l"<hexo-theme-yilia-l@noreply.github.com>;
抄送: "konelane"<w.yuanhe@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Kiritor/hexo-theme-yilia-l] 关于yilia-l主题的字体 (#1)



先告诉我秋梨膏是什么梗

**Comment by Kiritor** [comment]
关于你说的添加字体切换功能(配置文件开关)，闲时跟进下

**Comment by konelane** [comment]
谢谢大神！期待大神做出更好的作品٩( ๑╹ ꇴ╹)۶

**Comment by Kiritor** [comment]
> 谢谢大神！期待大神做出更好的作品٩( ๑╹ ꇴ╹)۶

研究下了，目前hexo博客暂不支持通过配置文件配置化切换字体， 但是可以引入字体，代码中调整
